// Disposable local PostgreSQL only; never reads .env or contacts Supabase.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { createRequire } from 'node:module';
const tools = process.env.MODERNTAP_PG_TOOLS;
for (const entitlements of [false, true]) test(`pilot migration, RLS and customer boundaries (entitlements ${entitlements})`, { skip: !tools, timeout: 60000 }, async () => {
  const requireTools = createRequire(path.join(tools, 'package.json'));
  const { default: EmbeddedPostgres } = await import(requireTools.resolve('embedded-postgres'));
  const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'moderntap-pilot-db-'));
  const socket = net.createServer(); await new Promise(r => socket.listen(0, '127.0.0.1', r));
  const port = socket.address().port; await new Promise(r => socket.close(r));
  const pg = new EmbeddedPostgres({ databaseDir: path.join(temp, 'data'), user: 'postgres', password: 'local-fixture', port, persistent: false, onLog() {}, onError() {}, initdbFlags: ['--locale=C', '--encoding=UTF8'], postgresFlags: ['-h', '127.0.0.1'] });
  let db;
  const connections = [];
  try {
    await pg.initialise(); await pg.start(); db = pg.getPgClient(); await db.connect();
    // Table shapes follow the read-only PostgREST schema inspection. Policies below
    // deliberately include a permissive policy to verify the new restrictive boundary.
    await db.query(`
      create role anon; create role authenticated; create role service_role bypassrls;
      create schema auth;
      create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
      create function auth.role() returns text language sql as $$ select nullif(current_setting('request.jwt.claim.role',true),'') $$;
      grant usage on schema public,auth to anon,authenticated,service_role;
      grant execute on all functions in schema auth to anon,authenticated,service_role;
      create table businesses(id uuid primary key default gen_random_uuid(), owner_id uuid not null, name text not null, created_at timestamptz not null default now());
      create table plaques(id uuid primary key default gen_random_uuid(), business_id uuid not null references businesses(id), name text not null, code text not null unique, destination_url text not null, active boolean not null default true, created_at timestamptz not null default now(), mode text not null default 'direct_link', purpose text not null default 'general');
      create table tap_events(id bigint generated by default as identity primary key, plaque_id uuid not null references plaques(id), user_agent text, created_at timestamptz not null default now());
      create table subscriptions(id uuid primary key default gen_random_uuid(), business_id uuid not null unique references businesses(id), status text not null default 'inactive', stripe_subscription_id text, stripe_customer_id text, stripe_price_id text);
      grant all on businesses,plaques,subscriptions to authenticated,service_role;
      grant select on businesses to anon;
      alter table businesses enable row level security;
      create policy fixture_owner on businesses for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
      create policy fixture_permissive on businesses for select to anon,authenticated using(true);
    `);
    if (entitlements) await db.query(fs.readFileSync('supabase/migrations/20260925_enforce_active_plaque_limits.sql', 'utf8'));
    await db.query(fs.readFileSync('supabase/migrations/20260929_add_admin_pilots.sql', 'utf8'));
    const owner = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
    const other = 'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
    async function session(role, uid = '') {
      const c = pg.getPgClient(); await c.connect(); connections.push(c);
      await c.query(`set role ${role}`);
      await c.query("select set_config('request.jwt.claim.role',$1,false),set_config('request.jwt.claim.sub',$2,false)", [role, uid]); return c;
    }
    const admin = await session('service_role'); const customer = await session('authenticated', owner);
    const stranger = await session('authenticated', other); const anon = await session('anon');
    const pilot = (await admin.query("insert into businesses(name,is_pilot,trial_started_at,trial_ends_at,pilot_reviews_start,pilot_rating_start) values('Lorenzo pilot',true,'2026-09-29','2026-10-29',125,4.5) returning id")).rows[0].id;
    const normal = (await customer.query("insert into businesses(name,owner_id) values('Owned',$1) returning id", [owner])).rows[0].id;
    const unownedCustomer = (await db.query("insert into businesses(name,owner_id) values('Other',$1) returning id", [other])).rows[0].id;
    assert.equal((await customer.query('select id from businesses')).rows.length, 1);
    assert.equal((await stranger.query('select id from businesses')).rows[0].id, unownedCustomer);
    assert.equal((await anon.query('select id from businesses')).rowCount, 0);
    assert.equal((await customer.query('select id from businesses where id=$1', [pilot])).rowCount, 0);
    assert.equal((await customer.query('update businesses set owner_id=$1 where id=$2 returning id', [owner, pilot])).rowCount, 0);
    await customer.query("update businesses set name='Still editable' where id=$1", [normal]);
    await assert.rejects(customer.query('update businesses set is_pilot=true where id=$1', [normal]), /administrator/);
    await assert.rejects(customer.query("insert into businesses(owner_id,name,is_pilot) values($1,'Spoof',true)", [owner]), /administrator/);
    await assert.rejects(customer.query("update businesses set pilot_notes='Spoof' where id=$1", [normal]), /administrator/);
    await assert.rejects(customer.query('update businesses set owner_id=null where id=$1', [normal]), /row-level security/);
    await admin.query("insert into plaques(business_id,name,code,destination_url,placement) select $1,'Table '||i,'CODE'||i,'https://example.test/review','table' from generate_series(1,24) i", [pilot]);
    assert.equal((await db.query('select count(*)::int as n from plaques where business_id=$1 and active', [pilot])).rows[0].n, 24);
    await assert.rejects(admin.query("insert into plaques(business_id,name,code,destination_url,placement) values($1,'Bad','BAD','https://example.test','wall')", [pilot]), /check constraint/);
    // A collision rolls back the whole batch, including any trigger counter updates.
    await assert.rejects(admin.query("insert into plaques(business_id,name,code,destination_url) values($1,'New','NEW','https://example.test'),($1,'Duplicate','CODE1','https://example.test')", [pilot]), /unique constraint/);
    assert.equal((await db.query("select id from plaques where code='NEW'")).rowCount, 0);
    if (entitlements) {
      assert.equal((await db.query('select active_count from moderntap_private.plaque_usage where business_id=$1', [pilot])).rows[0].active_count, 24);
      await admin.query("update plaques set active=false where code='CODE1'");
      assert.equal((await db.query('select active_count from moderntap_private.plaque_usage where business_id=$1', [pilot])).rows[0].active_count, 23);
      await admin.query("update plaques set active=true where code='CODE1'");
      await assert.rejects(admin.query("insert into plaques(business_id,name,code,destination_url) values($1,'No subscription','NORMAL','https://example.test')", [normal]), /MT_SUBSCRIPTION_REQUIRED/);
      await assert.rejects(customer.query("insert into plaques(business_id,name,code,destination_url) values($1,'No subscription','NORMAL','https://example.test')", [normal]), /MT_SUBSCRIPTION_REQUIRED/);
      // Even an owner assigned to a pilot cannot use the service-role bypass.
      await admin.query('update businesses set owner_id=$1 where id=$2', [owner, pilot]);
      await assert.rejects(customer.query("insert into plaques(business_id,name,code,destination_url) values($1,'Owner pilot','OWNER-PILOT','https://example.test')", [pilot]), /MT_SUBSCRIPTION_REQUIRED/);
      await db.query("insert into moderntap_private.price_entitlements values('price_fixture','starter',5)");
      await admin.query("insert into subscriptions(business_id,status,stripe_subscription_id,stripe_price_id) values($1,'active','sub_fixture','price_fixture')", [normal]);
      await customer.query("insert into plaques(business_id,name,code,destination_url) select $1,'Customer '||i,'NORMAL'||i,'https://example.test' from generate_series(1,5) i", [normal]);
      await assert.rejects(customer.query("insert into plaques(business_id,name,code,destination_url) values($1,'Over limit','OVER','https://example.test')", [normal]), /MT_PLAQUE_LIMIT/);
      await assert.rejects(admin.query("insert into plaques(business_id,name,code,destination_url) values($1,'Admin over','OVER','https://example.test')", [normal]), /MT_PLAQUE_LIMIT/);
    } else {
      assert.equal((await db.query("select to_regprocedure('moderntap_private.guard_plaque_capacity()') as guard")).rows[0].guard, null);
      await customer.query("insert into plaques(business_id,name,code,destination_url) values($1,'Legacy','LEGACY','https://example.test')", [normal]);
    }
    assert.equal((await db.query('select count(*)::int as n from subscriptions where business_id=$1', [pilot])).rows[0].n, 0);
  } finally {
    for (const c of connections) await c.end();
    if (db) await db.end();
    await pg.stop().catch(() => {}); fs.rmSync(temp, { recursive: true, force: true });
  }
});
