"use client";
import { useRef, useState } from "react";
import Link from "next/link";
import SmartPageView from "@/components/smart-page/smart-page-view";
import { normalizePresentation, resolvePresentation } from "@/lib/smart-page-presentation";
import { SMART_PAGE_DESIGNS } from "@/lib/smart-page-designs";
import type { ThemePreset } from "@/lib/smart-page-appearance";
import { DEMO_ACTIONS, DEMO_BUSINESS, DEMO_DAYS, DEMO_PLAQUES } from "@/lib/demo/fixtures";

const steps = [
  ["The customer taps", "One tap. Everything they need.", "A customer at Cedar & Stone opens the café’s world with a tap."],
  ["The business controls it", "Change where your plaques lead anytime.", "The same plaque. A new destination. No physical replacement needed."],
  ["The activity tells a story", "See how customers interact.", "Understand taps and selected actions, from your busiest moment to your most-used plaque."],
  ["Build the experience", "Make every tap feel like your brand.", "Choose a design, add your words, and give customers a clear next step."],
  ["Ready for your business", "You're ready to use ModernTap.", "A welcoming customer experience. An easier way to manage it."],
];
const themes: ThemePreset[] = ["bistro", "espresso", "studio", "boutique", "coastal", "modern", "bold"];
const logo = `data:image/svg+xml,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 160 100"><rect width="160" height="100" rx="8" fill="#FFFCF7"/><path d="M68 19q12-16 24 0-12 16-24 0" fill="none" stroke="#594334" stroke-width="1.5"/><text x="80" y="64" text-anchor="middle" font-family="Georgia,serif" font-size="36" fill="#40251D">C&amp;S</text><text x="80" y="84" text-anchor="middle" font-family="sans-serif" font-size="8" letter-spacing="3" fill="#40251D">NEIGHBORHOOD CAFÉ</text></svg>')}`;
export default function TourShell() {
  const [step, setStep] = useState(0);
  const [tapped, setTapped] = useState(false);
  const [theme, setTheme] = useState<ThemePreset>("bistro");
  const [heading, setHeading] = useState("Cedar & Stone Café");
  const [selected, setSelected] = useState("menu");
  const [icons, setIcons] = useState(true);
  const [mode, setMode] = useState("Smart Page");
  const [destination, setDestination] = useState("Café menu & welcome");
  const [period, setPeriod] = useState<7 | 14>(7);
  const [action, setAction] = useState("");
  const [message, setMessage] = useState("");
  const title = useRef<HTMLHeadingElement>(null);
  function move(next: number) { setStep(next); setMessage(""); requestAnimationFrame(() => title.current?.focus()); }
  const presentation = resolvePresentation(normalizePresentation({ presentation_version: 2, theme_preset: theme, content_alignment: SMART_PAGE_DESIGNS[theme].alignment, logo_size: "small" }));
  const actions = DEMO_ACTIONS.map(item => ({ id: item.icon, label: item.label, href: "", iconKey: icons || item.icon !== selected ? item.icon : null }));
  function demoAction(id: string) { const label = actions.find(item => item.id === id)!.label; setAction(label); setSelected(id); setMessage(`Demo: ${label} selected. No website opened or activity recorded.`); }
  const page = <div className="mx-auto w-full max-w-[390px] overflow-hidden rounded-[30px] border-[6px] border-[#253c3c] shadow-xl"><SmartPageView heading={heading} subheading="Good coffee. Good company. Find your next stop." logoSrc={logo} appearance={presentation} actions={actions} preview onDemoAction={demoAction}/></div>;
  return <main className="min-h-svh bg-[#f3f7f9] px-4 py-7 sm:px-6">
    <div className="mx-auto max-w-5xl">
      <header className="flex items-center justify-between gap-4"><p className="mt-kicker">ModernTap · A minute at Cedar & Stone</p><Link href="/billing" className="shrink-0 text-sm font-semibold text-[#0f766e] underline">Skip Tour</Link></header>
      <ol aria-label="Tour progress" className="mt-6 flex gap-2">{steps.map(([label], i) => <li key={label} aria-current={step === i ? "step" : undefined} className={`h-1 flex-1 rounded-full ${i <= step ? "bg-[#0f8f8a]" : "bg-slate-200"}`}><span className="sr-only">{i + 1}. {label}</span></li>)}</ol>
      <p className="mt-7 text-xs font-semibold uppercase tracking-widest text-[#0f766e]">{step + 1} / 5 · {steps[step][0]}</p>
      <h1 ref={title} tabIndex={-1} className="mt-3 max-w-2xl text-3xl font-semibold tracking-tight text-[#17324d] outline-none sm:text-4xl">{steps[step][1]}</h1>
      <p className="mt-3 max-w-xl text-sm leading-6 text-slate-600">{steps[step][2]}</p>
      <p className="mt-3 text-xs text-slate-500">Fictional demo · no live changes</p>
      <div className="mt-6 rounded-2xl border border-[#dbe4ea] bg-white p-4 sm:p-7">
        {step === 0 && <div className="grid items-center gap-8 md:grid-cols-2"><section className="rounded-xl bg-[#eee4d5] p-6 text-[#40251D]"><p className="text-xs uppercase tracking-[0.2em]">{DEMO_BUSINESS}</p><h2 className="mt-4 font-serif text-3xl">Your usual table.<br/>A new way to connect.</h2><div className="mt-8 border-b-8 border-[#92725a] pb-5"><div className="mx-auto max-w-52 rounded-t-[60px] border border-[#c9b59f] bg-[#fffcf7] px-5 py-8 text-center shadow-lg"><span aria-hidden="true" className="font-serif text-4xl">C&S</span><p className="mt-4 text-xs uppercase tracking-widest">Menu · Reviews · More</p><button onClick={() => { setTapped(true); setMessage("Demo tap: the café’s Smart Page opens. Try an action."); }} className="mt-6 rounded-full bg-[#40251D] px-4 py-3 text-sm font-semibold text-white motion-safe:transition-transform motion-safe:hover:scale-105">Tap the demo plaque</button></div></div><p className="mt-4 text-sm leading-6">At the counter or beside a table, your plaque connects customers to what matters.</p></section><div>{tapped ? page : <div className="mx-auto grid min-h-80 max-w-sm place-items-center rounded-[30px] border-2 border-dashed border-[#c6d7d6] bg-[#f7faf9] p-8 text-center"><div><span aria-hidden="true" className="text-4xl text-[#0f766e]">↗</span><p className="mt-4 font-semibold text-[#17324d]">Tap the plaque to open<br/>the customer experience.</p></div></div>}</div></div>}
        {step === 1 && <div className="grid gap-7 md:grid-cols-2"><section><p className="mt-kicker">My Plaques · {DEMO_BUSINESS}</p><h2 className="mt-3 text-2xl font-semibold">Front Counter</h2><span className="mt-3 inline-block rounded-full bg-[#dffaf8] px-3 py-1 text-xs text-[#0f766e]">Active · {mode}</span><div className="mt-6 rounded-xl border-2 border-[#0f8f8a]/30 bg-[#f5faf8] p-5"><p className="text-xs uppercase tracking-widest">Current destination</p><p className="mt-3 text-lg font-semibold" aria-live="polite">{destination}</p><p className="mt-3 text-xs text-slate-500">One permanent plaque. You decide what opens.</p></div></section><section className="rounded-xl border p-5"><h3 className="font-semibold">Try a different destination</h3><label className="mt-5 block text-sm">Experience<select aria-label="Demo experience" value={mode} onChange={e => { setMode(e.target.value); setMessage("Demo experience updated. Your physical plaque stays the same."); }} className="mt-2 block w-full rounded-lg border p-3"><option>Smart Page</option><option>Direct Link</option></select></label><label className="mt-4 block text-sm">Send customers to<select aria-label="Demo destination" value={destination} onChange={e => { setDestination(e.target.value); setMessage("Demo destination updated. The physical plaque stays the same."); }} className="mt-2 block w-full rounded-lg border p-3"><option>Café menu & welcome</option><option>Seasonal menu</option><option>Review destination</option></select></label><p className="mt-4 text-xs leading-5 text-slate-500">Smart Pages offer several actions. Direct Links open one destination. This example changes only on your screen.</p></section></div>}
        {step === 2 && <>
          <div className="mb-5 flex flex-wrap gap-2" role="group" aria-label="Demo analytics period">{([7, 14] as const).map(days => <button key={days} aria-pressed={period === days} onClick={() => setPeriod(days)} className={`rounded-lg border px-4 py-3 text-sm ${period === days ? "bg-[#17324d] text-white" : "bg-white text-slate-600"}`}>Last {days} Days</button>)}</div>
          <div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-[#dffaf8] p-5"><p className="text-sm">Taps</p><p className="mt-2 text-3xl font-bold">{period === 7 ? 280 : 560}</p></div><div className="rounded-xl bg-[#f3f7f9] p-5"><p className="text-sm">Smart Page Actions</p><p className="mt-2 text-3xl font-bold">{period === 7 ? 96 : 192}</p></div></div>
          <div className="mt-4 border-l-2 border-[#0f8f8a] pl-4 text-sm leading-6"><p>Customer taps → opens your page → chooses an action</p><p className="text-slate-500">{tapped ? `Your demo: Front Counter tap${action ? ` → ${action}` : ""}.` : "Example: Front Counter → View Menu."} These are the interactions ModernTap can record.</p></div>
          <h3 className="mt-6 font-semibold">Activity trend</h3><div className="mt-4 flex h-40 items-end gap-2" aria-label="Fictional taps over time">{DEMO_DAYS.map((value, i) => <div key={i} className="flex min-w-0 flex-1 flex-col items-center justify-end text-xs"><span>{value * (period / 7)}</span><div className="mt-1 w-full rounded-t bg-[#16c7c0]" style={{ height: value * 1.5 }}/><span className="mt-2">{period === 7 ? `D${i + 1}` : `${i * 2 + 1}–${i * 2 + 2}`}</span></div>)}</div>
          <div className="mt-6 grid gap-5 sm:grid-cols-2"><section><h3 className="font-semibold">Top Plaques</h3>{DEMO_PLAQUES.slice(0, 3).map(p => <p key={p.id} className="flex justify-between gap-3 border-b py-2 text-sm"><span>{p.name}</span><strong className="shrink-0">{p.taps * (period / 7)} taps</strong></p>)}</section><section><h3 className="font-semibold">Busiest Time</h3><p className="mt-2 text-xl font-bold">12 PM – 1 PM</p><p className="mt-3 text-xs leading-5 text-slate-500">Taps and action selections are not completed purchases, completed Google reviews, or revenue.</p></section></div>
        </>}
        {step === 3 && <div className="grid items-start gap-7 md:grid-cols-2"><section className="rounded-xl border p-5"><p className="mt-kicker">Your Smart Page · live demo</p><label className="mt-5 block text-sm font-semibold">Design<select aria-label="Demo design" value={theme} onChange={e => setTheme(e.target.value as ThemePreset)} className="mt-2 block w-full rounded-lg border p-3 capitalize">{themes.map(key => <option key={key} value={key}>{key}</option>)}</select></label><p className="mt-2 text-xs text-slate-500">{SMART_PAGE_DESIGNS[theme].description}</p><label className="mt-5 block text-sm font-semibold">Heading<input aria-label="Demo heading" value={heading} maxLength={100} onChange={e => setHeading(e.target.value)} className="mt-2 block w-full rounded-lg border p-3"/></label><label className="mt-5 block text-sm font-semibold">Action<select aria-label="Demo action" value={selected} onChange={e => { setSelected(e.target.value); setIcons(true); }} className="mt-2 block w-full rounded-lg border p-3">{DEMO_ACTIONS.map(item => <option key={item.icon} value={item.icon}>{item.label}</option>)}</select></label><label className="mt-4 flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={icons} onChange={e => setIcons(e.target.checked)}/>Show an icon for this action</label><p className="mt-4 text-xs leading-5 text-slate-500">This is the same design system as your real Smart Page builder. Changes here are local to the tour.</p></section>{page}</div>}
        {step === 4 && <div className="py-7 text-center"><p className="font-serif text-3xl text-[#17324d]">From a single tap<br/>to a thoughtful experience.</p><ol className="mt-8 flex flex-wrap justify-center gap-3">{["Tap", "Customer Experience", "Engagement", "Insights", "Easy Updates"].map((text, index) => <li key={text} className="rounded-lg border bg-[#f5faf8] px-4 py-3 text-sm text-[#204d42]"><span className="mr-2 text-xs">{index + 1}</span>{text}</li>)}</ol><p className="mx-auto mt-6 max-w-md text-sm leading-6 text-slate-600">Your business. Your destinations. A clearer view of customer activity.</p></div>}
        <p role="status" className="mt-4 min-h-5 text-sm text-[#0f766e]">{message}</p>
      </div>
      <nav aria-label="Tour navigation" className="mt-6 flex items-center justify-between gap-3"><div>{step > 0 && <button type="button" onClick={() => move(step - 1)} className="mt-secondary-action">Back</button>}</div>{step < 4 ? <button type="button" onClick={() => move(step + 1)} className="mt-primary-action">{step === 3 ? "Finish Tour" : "Next →"}</button> : <Link href="/billing" className="mt-primary-action">Choose Your Plan</Link>}</nav>
    </div>
  </main>;
}
